### ISSUE TITLE
Can't build 0.25 on Alpine Linux

### ISSUE THREAD

**Issue by jeffrizzo** [analogdevicesinc/libiio#1178]
When trying to build 0.25 under Docker using Alpine Linux (it built in version 0.23), I got this error, so I'm reporting it as requested:

```
#11 8.002 -- Looking for pthread_setname_np
#11 8.206 -- Looking for pthread_setname_np - found
#11 8.212 -- found unknown distribution Alpine Linux, Version : VERSION_ID=3.20.0
#11 8.212 CMake Error at cmake/LinuxPackaging.cmake:35 (message):
#11 8.212   please report an error to
#11 8.212   https:\/\/github.com\/analogdevicesinc\/libiio\/issues
#11 8.212 Call Stack (most recent call first):
#11 8.212   CMakeLists.txt:650 (include)
```

**Comment by tfcollins** [comment]
Can you provide your cmake command with arguments you are using? And Alpine version?

**Comment by rgetz** [comment]
@jeffrizzo  This is expected - since the code doesn't support Alpine yet when building packages.

https://github.com/analogdevicesinc/libiio/blob/main/cmake/LinuxPackaging.cmake#L23-L33

Since Alpine doesn't use deb or rpm (it uses apk) - I assume you shouldn't build packages, and can just leave that off? 

Thanks
-Robin

**Comment by cz172638** [comment]
https://git.alpinelinux.org/aports/tree/testing/libiio/APKBUILD

**Comment by tfcollins** [comment]
@cz172638 Can we close this issue? Assuming the package works...

**Comment by cz172638** [comment]
i think so, i've put link to apkbuild, so @jeffrizzo can take inspiration and eventually lobby for getting libiio package from `testing` to `community`
