### ISSUE TITLE
Failing to compile libiio

### ISSUE THREAD

**Issue by alexanderthefox** [analogdevicesinc/libiio#194]
Hello, 
I tried to compile libiio on my fresh Ubuntu 18.04.1., but I got the following message during compiling with cmake:

alexander@alexander-HP-Compaq-6530b-GW688AV:~/libiio$ cmake .
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:264 (message):
  The selected backends require libxml2 and the XML backend to be enabled
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen missing components:  dot
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of struct usb_functionfs_descs_head_v2
-- Check size of struct usb_functionfs_descs_head_v2 - done
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - found
-- Configuring incomplete, errors occurred!
See also "/home/alexander/libiio/CmakeFiles/CmakeOutput.log"

I'm an absolute beginner with linux. So my question is: What went wrong and how could I make the compiling work successfully?

It would be great to get help.

Thanks.
Alexander

**Comment by mhennerich** [comment]
You need to install libxml2

**Comment by alexanderthefox** [comment]
Hi mhennerich,

I just installed gnuradio with the command:
Sudo apt install gnuradio


How can I install libxml2?

**Comment by mhennerich** [comment]
Did you try
#sudo apt-get install libxml2

?

**Comment by commodo** [comment]
As a general comment: for building libiio & dependencies you can check our Travis CI scripts.
Dependencies are  https://github.com/analogdevicesinc/libiio/blob/master/CI/travis/before_install_linux
Building the package: https://github.com/analogdevicesinc/libiio/blob/master/CI/travis/make_linux

Be aware that `make package` is more related to packaging than building.

This issue seems resolved, so I'll close it. But if there are any open things related to it, feel free to open.

Thanks
Alex
