### ISSUE TITLE
Different fetch frequency for mutliple application with iiod

### ISSUE THREAD

**Issue by ChenhuiZhang** [analogdevicesinc/libiio#743]
Hi,

I check below picture from Document: https://wiki.analog.com/_media/resources/tools-software/linux-software/libiio/internals/libiio_readbuf_command.png?w=700&tok=734270. It seems if we have two application, e.g. A and B, they both want to fetch N samples of data but in different frequency. if A request the sensor data in 8 times per second, but then B request 1 time per second, then the A will be forced to lower the request speed, it will only get 1/8 N samples data and the left 7/8 data is lost, correct?  

I thought the iiod will do in another way, e.g. if A request N/8 samples, and B request N samples, the iiod will get a highest common factor of (N/8, N) = N/8, so in iiod, it will call buffer_refill() to get N/8 samples one time, then dispatch to A, and save it in iiod buffer, when the buffer reach total N samples, then dispatch to B immediately. Of cause, if unluckily the worst case is the highest common factor is 1 which will make things less efficient. 

I know that's may quite different design with current one, but could someone share any thoughts about this? The main concern for the current design is: the application A will easily impact if some other application request the same sensor data.

P.S. both A and B will call buffer_refill() in block mode.

Best Regards,
Hermes

**Comment by pcercuei** [comment]
Hi Hermes,

The data within a IIO buffer must be contiguous. This is a hard requirement. Therefore it is not possible to call iio_buffer_refill() to get N/8 samples at a time, because then in your example the application B might obtain non-contiguous data in its buffer.

One possible solution, would be that IIOD could continue streaming to application A from the same IIO buffer without refilling, with a x*N/8 offset, until it reaches the end of the buffer or until application B requests a new set of samples.

Cheers,
-Paul
