### ISSUE TITLE
No IIO context found with iio_info and a Adalm-Pluto

### ISSUE THREAD

**Issue by RGerzaguet** [analogdevicesinc/libiio#752]
Hello there,

I have an issue with libbio which is surprising. After compilation of the lib I cannot get backend information when I do an `iio_info -S` with the last version of libiio (0.23)

A reproductible example on my machine (Ubuntu 18) with a Pluto plugged

```
~:  ./iio_info -S
Library version: 0.23 (git tag: 92d6a35)
Compiled with backends: local xml ip usb
No IIO context found.
```

While, 
```
./iio_info -u 'ip:192.168.2.1'
Library version: 0.23 (git tag: 92d6a35)
Compiled with backends: local xml ip usb
IIO context created with network backend.
Backend version: 0.23 (git tag: v0.23)
Backend description string: 192.168.2.1 Linux (none) 5.4.0-00535-g9c04de11ae53 #1 SMP PREEMPT Fri Aug 20 13:01:03 CEST 2021 armv7l
IIO context has 9 attributes:
..... * Lot of stuff here*
```

AFAIK, the previous libiio lib I used worked very well (`iio_info -a` detects IP and USB). But I don't understand why it does not work anymore.
It seems that I miss something obvious here but I struggle to find pointers on which part I am doing wrong. Any idea ?

**Comment by cygonz0** [comment]
try it with `-s` (lower case)

**Comment by youcangetduffed** [comment]
> 

hey how are you my name is marshond waddell i go by lucky..everthing about this event..the woman i love lindsey white played me we have three kids together and we live with each other..  jus for her to do this i got drugged and i almost died because she wanted to go behind my back and have a lil fun..im an honest guy i love my children and my sneaking fiance.. all my emails are blocked and she has a sister named amanda roll thats good at hacking... plz i need to know about this event and what all happened and who all was involved plzz help me..i cant do this no more with her and i cant get proof of what shes doin..im on medication now because she says im delusional if some how u can help me know the truth it will vbe a big help plzz
