### ISSUE TITLE
timestamp API

### ISSUE THREAD

**Issue by catkira** [analogdevicesinc/libiio#860]
A possible way to support timestamps would be to add the following functions to libiio
```c
struct meta_command
{
    uint64 timestamp,
    uint64 num_samples,
    enum type
    {
        send_timed,
        send_untimed  // timestamp is ignored
        receive_timed,
        receive_untimed
    },
    uint64 command_counter
};

set_timestamp_mode(bool mode)
{
    // write mode to mode iio attribute of timestamper core
   // if mode is false, everything should behave like now
}

write_timed_command(meta_command cmd)
{
    // write cmd to command iio channel of timestamper core
}
```
For getting the timestamp from HDL to user there could be a timestamp added to each block. The disadvantage of this would be, that the blocksize would not be num_samples * sample_size anymore. Also inside the axi_dmac it would be a bit more complicated, because the internal fifo size is calculated like burst_size * num_bursts.
I think the cleanest way would be to add a receive channel to the timestamper module, that gives out a timestamp for every meta command. The difficulty here would be to match the received timestamp to the meta command (probably easy for sync reads and more difficult for async/non-blocking reads). One could add a command_id to the meta_command struct to make this easier. Or add a get_timestamp() function to libiio that matches timestamps to received data blocks. But one would have to make sure, that this matching also works correctly in case of overflows in the HDL. So adding a command_counter to meta_command would probably be the easiest. The command_counter value could then also just be a field of the received_timestamp struct
```c
struct received_timestamp
{
    uint64 timestamp,
    command_counter
}

get_received_timestamp(received_timestamp &timestamp)
{
    // read an item from the rx timestamp channel of the timestamper core
}
```

**Comment by pcercuei** [comment]
I disagree with your suggestion, the timestamp value should not be written by the DMA to the samples buffer. Instead, it should be written by the IP to a separate hardware register, that the kernel can read in the IRQ handler, and provide to the userspace through a device or buffer attribute. That would make things way simpler: the application would just need to dequeue a block of samples, then optionally read the attribute.

Same for TX - the userspace would write a device/buffer "timestamp" attribute, which would cause the kernel to write to a register of the IP, that would control how the next buffer is transferred.

Note that I don't really think we need a "timestamp", but a "samples counter". Since we know the sample rate we can retrieve the timestamps anyway, and having a "samples counter" would make it much easier to detect DMA underruns / overruns.

**Comment by catkira** [comment]
Yes, I think my writing was not so clear. Mixing timstamps with data was only my first idea. But my second idea was
`I think the cleanest way would be to add a receive channel to the timestamper module, that gives out a timestamp for every meta command.`
With this I mean something similar as You suggest - I think. But it is not clear to me, what You mean by 'separate hardware register', a memory area in the FPGA that can be accessed via axi-gpio?
Just writing or reading a register would be problematic, because the following usecase should be supported:
(assuming samplerate of 1MSPS)
@t=0.5ms: send 1000 samples at t=1ms
@t=1.5ms: send 1000 samples at t=2ms

In this case, the tx command for the 2nd burst is issued, while the 1st burst is not yet completed. Therefore the command would need some kind of buffering in the fpga. Also, just a timestamp is not enough, the number of bytes requested would also need to be specified. Therefore I suggested the 'meta_command' struct that includes all these data.
For getting the meta_commands to the fpga, I would just add another axi_dmac component to the hdl code, so that the meta_commands could be send via a separate iio-channel to the hdl. For getting the meta information from hdl to user code, one could add another axi-dmac core which will also provide an iio-channel. The timestamper logic in hdl could be enabled/disabled via an iio-attribute. If it is disabled, the hdl behaves like now. That would make sure that existing applications wont get broken.

Relying on a sample rate should be possible in an ideal world. But if there are frequency changes it can get messy, thats why I think a real timestamp would be more robust.

I will make a state-graph of the FSM that I envision for the timestamper core, I think that would make my idea a bit more clear.

**Comment by pcercuei** [comment]
There's no need for buffering in the FPGA. The DMA should process the requests sequentially like it already does, and wait until the transfer time is reached if needed. So it does not need to know about any following request before the previous ones are finished.

The number of bytes does not need to be specified, just transfer the whole block of samples. If you want to transfer a non-standard number of samples, then just create a block of that size.

Adding a separate iio channel is a bad idea, there would be no way of matching the data from that channel to the samples of the main buffer. You only need to instruct the DMA to wait for a specified time before transferring a whole buffer, so a hardware register (appearing as a device/buffer attribute in userspace) looks appropriate to me.

Baseband frequency changes don't change the sample rate of your ADC. The sample rate does not change on-the-fly like that. Making the timestamp core work with samples count would work much better and be way more precise.

**Comment by catkira** [comment]
Ah yes, I meant sample rate changes not frequency changes. They can happen on the fly, ie in srsRAN during the login procedure. During cell search 1.92 MSPS is used. After a cell is found, the client (ue) will switch to the sample rate of the base station (eNB) and continue with that sample rate.

Yes, if the blocksize is can be variable in a range from 1 - 1M or so it should be ok. I did not study the driver code deep enough to be able to tell if thats possible -  but I trust You :)

In my meta_command struct is a command_counter, that the driver has to increment for every burst. That way the meta and data channel could be matched. 

A problem when not buffering burst meta data in hdl could arise, when there is no gap between two bursts, like in the example from before
'
(assuming samplerate of 1MSPS)
@t=0.5ms: send 1000 samples at t=1ms
@t=1.5ms: send 1000 samples at t=2ms
'
I imagine that fetching a new dma block takes some time during which samples will be missed.

**Comment by pcercuei** [comment]
The DMA cores already have hardware queues, and switching between one configured transfer to another is instant and does not cause samples to be missed.

**Comment by catkira** [comment]
Ah, You mean the 'storage-and-forward Data Buffer' in this diagramm?
![axi_dmac_block_diagram](https://user-images.githubusercontent.com/13425558/177396713-e70551bd-e6de-4e9a-b3c4-02738801a36f.png)

**Comment by catkira** [comment]
<img width="840" alt="timestamper" src="https://user-images.githubusercontent.com/13425558/177412874-b01fe8f5-fca9-4afd-bd6b-d6637a165ba2.PNG">

**Comment by pcercuei** [comment]
I don't really know what the FPGA program does, I just know that we already have a hardware queue for the DMA, and no samples are lost when the DMA switches from streaming one block of samples to another. So we already manage "consecutive burst writes" if you will.

You can manage things with just a single register for meta-data, if this register is read by the IP at the moment it starts streaming from a new block of samples. Then every time the DMA is done streaming from a block of samples, the driver can update the value of the register to the next transfer's setting. And since the timestamper is basically about pausing / unpausing the DMA until a special point in time is reached, the magic register could also be a new field in the DMA hardware descriptor.

As for using time vs. samples count... The example of a random software changing the sample rate isn't really valid IMHO. This software does not use timestamped buffers, and if it did, it would either not change the sample rate (keep the fast rate at all times), or handle it properly (not programming timestamped buffers when a sample rate change is under way). Using a samples counter just makes more sense, as it permits to be extremely precise in the time domain, and detect overruns/underruns.

**Comment by catkira** [comment]
I dont know the structure of the DMA driver in detail. But if there is no sample gap between two consecutive DMA transfers and if a block with meta-data could be added to the DMA descriptor, then this could work.
Some software also require the burst functionality to send or receive N samples _now_, how would You implement that? Have a second meta register that holds a flag which is "now" or "timestamp"?
Also if You have this functionality, it is necessary to return a timestamp to the user code? (for the case where You receive N samples _now_, because the user software needs to know when the samples were received) Would You also do this via an additional field in the DMA descriptor?

Can You post a link to the code line where the DMA descriptor would have to be modified? Is it very intrusive, do parts of the DMA driver in the linux kernel have to be modified?

**Comment by pcercuei** [comment]
If the samples counter simply represents the number of samples by which the next transfer should be delayed, then "now" is just "counter=0".

Programming transfers at a specific point in time, which you call "timestamping", is one mechanism. The other mechanism is tagging the RX buffers with a timestamp, to be able to know when exactly those RX buffers were received. Again, it would make sense to use a samples count value, because then you can detect gaps between buffers. You can compute the age of the RX buffer by comparing with the "live" samples counter, which would be a register updated by the IP every time a sample is received.

Whatever we choose to do, there *will* be driver changes needed, so whether or not changes are intrusive isn't really a problem.

You are thinking about having a "timestamper control logic" after the AXI DMA core. What I'm telling you is that the AXI DMA core could gain the "programming transfers" functionality, and the rest of the HDL wouldn't change.

**Comment by catkira** [comment]
Ah ok, now I understand Your idea better. Sounds doable.

My idea was motivated to be an add on which does not need any changes in existing drivers, just a new driver for the timestamper core. Your idea is probably more efficient and cleaner.

I will have a look at the dma hdl and linux code to see where changes would have to be made.

Then the first thing to do would probably, make modifications to the axi_dmac core for the tx case and write a test bench for it.

**Comment by catkira** [comment]
For integrating timestamp functionality into axi dmac, I think [this](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/dma/dma-axi-dmac.c?id=HEAD)file would have to be modified. Since it is already mainlined, isnt that a bit complicated? Everybody who wants to use it would have to create his own firmware with running buildroot until the the changes appear in the mainline kernel.

**Comment by catkira** [comment]
Changes in the hdl code:
[FLAG register](https://wiki.analog.com/resources/fpga/docs/axi_dmac#:~:text=The%20FLAGS%20(0x40C)%20register%20controls%20the%20behavior%20of%20the%20transfer.) will get another flag, i.e. BURST.

**Comment by catkira** [comment]
@pcercuei I found out that there are already some functions in the linux kernel, to attach meta data to a dma descriptor.
Do you think functions like [dmaengine_desc_attach_metadata ](https://01.org/linuxgraphics/gfx-docs/drm/driver-api/dmaengine/client.html#:~:text=int%20dmaengine_desc_attach_metadata(struct%20dma_async_tx_descriptor%20*desc%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20void%20*data%2C%20size_t%20len)%3B)can be useful here?

**Comment by pcercuei** [comment]
I didn't know about metadata support in the dmaengine framework, that's great!

So the axi-dmac driver could be improved to support meta-data, as well as the DMA API core, to add support for sample counters.
The various chip drivers (or common code to all devices using axi-dmac) can then register themselves as meta-data client or provider, and have the sample counters exported to userspace.

Finally, libiio (in the local backend) would use this information when dequeueing buffers to know when samples have been lost, and set this attribute if the enqueued buffer has to be transmitted at a precise time.

**Comment by catkira** [comment]
yes sounds good.

We can start with the [drivers/iio/frequency/cf_axi_dds.c](https://github.com/analogdevicesinc/linux/blob/master/drivers/iio/frequency/cf_axi_dds.c) chip driver. 
The [axi_dmac driver](https://github.com/torvalds/linux/blob/master/drivers/dma/dma-axi-dmac.c) would have to translate to meta data into some axi register writes that the axi_dmac hdl core receives. The hdl core would just need one new register for write sample offset and one for read sample offset.
I think the tx case is the easiest to implement, so the first test case could be to send bursts, every 10 ms or so. That can be verified by watching the ouput on a spectogram.
Can You define a timestamp(or "samplestamp") interface for libiio?

**Comment by pcercuei** [comment]
I don't think the API of libiio will be a problem. You could have something like:
```
int iio_block_set_enqueue_delay(block, nb_samples);

uint64_t iio_block_get_dequeue_timestamp(block);
```

**Comment by catkira** [comment]
Can 
```
int iio_block_set_enqueue_delay(block, nb_samples);
```
also be used for rx? If yes, `iio_block_get_dequeue_timestamp(block)` might not be needed.

**Comment by catkira** [comment]
@pcercuei  How should the nb_samples information reach industrialio-buffer-dma.c in the kernel? If its in iio_buffer_block struct it would only work for the mmap interface but not for the dma interface. Or do you also want to add nb_samples to the iio_dmabuf struct?

**Comment by pcercuei** [comment]
I'd think we could have that in the DMABUF API only.

And now that I think of it… Why do we need anything in the IP core to support programmed transfers?

If you want a transfer to happen in 2ms, then the application (or libiio) can compute the number of dummy samples needed to fit 2ms, and enqueue that number of dummy samples.

**Comment by mhennerich** [comment]
Well, in a lot of cases you want to synchronize your timestamping to an 1PPS or some other event.
Also you can't assume that your streaming can keep up with the baseband rate.
So in a TDD application you would prepare a slot, queue it and have some HW IP release it at a certain time.

**Comment by catkira** [comment]
yes, if everything can keep up with the full uninterrupted data rate, then the axi_dmac would not need to be changed. But the AD9361 can do 2x 60 MSPS tx and 2x 60 MSPS rx and some ADRVs even more. So thats already much more than GBit ethernet can handle.
I think even if the app is not TDD, just FDD 4G/5G then its also useful to have timestamping, because the phy is still working with slots. 
Having no hdl timestamp support would also mean, that everything gets shifted in time once a few samples are lost. With timestamp support in hdl, lost samples would only have a local effect and the connection is not completely lost.

**Comment by pcercuei** [comment]
@mhennerich but enqueueing an empty buffer is a "free" operation, since we can fill it once and then enqueue it endlessly. IIOD could have a command "enqueue X dummy samples", so that you wouldn't transfer any data.

Unless you mean that the DMA itself cannot keep up with the baseband rate.

@catkira the mmap interface is never going to get upstream, that's what the dmabuf interface is being designed for. Once it is upstream, I believe ADI's kernel will support both, but the mmap interface will be marked as deprecated.

**Comment by catkira** [comment]
@mhennerich yes that could work. the axi_dmac core is connected to a HPC interface, which has a sustained data rate of about 300-400 MB/s 
https://xilinx.github.io/Embedded-Design-Tutorials/docs/2021.1/build/html/docs/User_Guides/SPA-UG/docs/6-evaluating-high-performance-ports.html

My calculation would be:
60 MSPS, 4 byte per Sample (2 byte I and 2 byte Q) => 240 MB/s for a single channel

but its already close and if there is no overflow detection for the dma transfer, the whole thing might lose synchronization without noticing it.

**Comment by pcercuei** [comment]
@catkira we do have ADCs and DACs that can deliver GSPS, so if the HPC interface is limited to 300-400 MB/s, then we really do need to handle this in the IP core.

**Comment by catkira** [comment]
> @catkira these are two different kernel interfaces, yes. The DMABUF one is the one I am trying to get upstream. It is not yet in ADI's kernel.

Where can I find the linux kernel with DMABUF support? Or is it not usable yet?

**Comment by catkira** [comment]
Since DMABUF probably takes a while to get upstreamed, its best to start implementing the timestamp API using the MMAP interface.

@rgetz @mhennerich @pcercuei I want to push this forward now and hopefully finish it by the end of next month. It would be good if somebody from ADI does the fundamental design decisions so that it can easily be merged into the ADI repos later. I would help imlementing things and participate in the design discussions.
If the timestamp API is not a priority for ADI at this time, I would go ahead and implement it and decide everything myself so that it works for my purpose. In that case the timestamp API probably wont get merged into the ADI repo because I dont have all possible use cases in mind.

**Comment by catkira** [comment]
This is how `iio_block` looks currently
```c
struct iio_block {
	struct iio_buffer *buffer;
	struct iio_block_pdata *pdata;
	size_t size;
	void *data;

	struct iio_task_token *token, *old_token;
	size_t bytes_used;
	bool cyclic;
};
```
I would make it
```c
struct iio_block {
	struct iio_buffer *buffer;
	struct iio_block_pdata *pdata;
	size_t size;
	void *data;

	struct iio_task_token *token, *old_token;
	size_t bytes_used;
	bool cyclic;
        long time;
        long flags;
};
```
For tx `long time` would hold the requested start time in ticks (sample count). For rx it would hold the receive time.
`long flags` would hold control flags, ie for tx `SEND_NOW`, `SEND_SCHEDULED` for rx they could be `RECEIVE_NOW`, `RECEIVE_SCHEDULED` and for the response block `TIME_PAST`, `ON_TIME`, `OVERFLOW`.

There would also need to be a possibility to get the timer (counter) value without sending or receiving anything. Because applications need that for the first timed command. Soapy has an abstraction for that which look like this
```c
long long getHardwareTime(const std::string &what = "") const;
void setHardwareTime(const long long timeNs, const std::string &what = "");
```
It could be done using the existing iio-api by just sending or receiving a block with bytes_used=0.

@pcercuei do You endorse this proposal?

**Comment by pcercuei** [comment]
There's no point discussing how to implement it in libiio, before we have a proof-of-concept working with HDL code, and kernel drivers; because then the libiio interface will depend on what API is offered  by the kernel...

**Comment by catkira** [comment]
Thats a chicken-egg-problem. Ideally the front and backend are developed at the same time so that the whole thing can be tested. But it seems that the hdl people of ADI are not interested in participating, so that part I will have to do alone. But maybe there is a chance to agree on a timestamp api for libiio. I prefer not to maintain private forks, I rather like to get stuff merged with PRs.

**Comment by pcercuei** [comment]
It is not a chicken-egg problem. Doing things out-of-order will most certainly result in twice the amount of work.

HDL people at ADI have their own agenda, you know. I'll see if we can organize something though.

**Comment by catkira** [comment]
Seems like the hdl guys are busy with other things. The timestamp feature has been discussed here on and off during the last couple of years, so it probably does not make sense to wait for an initiative. I will do the timestamp stuff myself then, this means unfortunately that I have to maintain forks of the hdl, buildroot, linux and libiio repo :/

**Comment by mhennerich** [comment]
Hi Benjamin,
scheduling a meeting with our HDL folks is on my todo list. Unfortunately last week I came back from a 2 week vacation, and I'm under water with quite a few things at the moment. We're happy to accept contributions for libiio, linux and HDL if we see them useful and maintainable. I think the timestamp infrastructure will definitely fall into this category. Ideally the HDL work should be discussed on the HDL forum, and I don't know their capacity and bandwidth to start working on this right away. This or the other way it would be good to have some alignment here. I'll set something up this week to discuss with them.

-Michael

**Comment by rgetz** [comment]
>the timestamp value should not be written by the DMA to the samples buffer.  Instead, it should be written by the IP to a separate hardware register, that the kernel can read in the IRQ handler, and provide to the userspace through a device or buffer attribute.

If the interface IP writes a sample count to a hardware registers - that the IRQ handler provides to user space through an attribute - how do you know if you are synchronous? (between buffers and timestamps?) I order to guarantee alignment between buffers and timestamps (or other meta data) doesn't it need to be managed in a single merged stream?

A single stream is how:
- Ettus solved problem in [CHDR](https://files.ettus.com/manual/page_rtp.html)  [latest spec[(https://files.ettus.com/app_notes/RFNoC_Specification.pdf#page=12)
- Industry solved in [VITA 49](https://wiki.ice-online.com/ICE_VITA_49.0_Radio_Transport_Ethernet_Packet_Specification) which is overkill - which is why most people don't use it - but is still a single stream for data + metadata
- Industry solved in [SigMF](https://github.com/gnuradio/SigMF/blob/sigmf-v1.x/sigmf-spec.md) where you can have metadata  per dataset.

Otherwise - how to manage the timestamp and the buffer from an application standpoint?

It's most important - not from a simple time stamping on a single device - use case - but check out use cases in [Ettus doc](https://kb.ettus.com/Synchronizing_USRP_Events_Using_Timed_Commands_in_UHD):
- Configuring multiple channels of a single to change frequency simultaneously (on devices like ADRV9002); or NCOs on AD9081; or control GPIOs (on the FPGA).
- Configuring the channels on multiple radios to synchronously retune and ensure a predictable phase offset between channels (think multiple Quad boards).
- Coordinating a simultaneous change of gain or frequency in a radio.
- Scheduling frequency hopping at set time increments.
- Transmit phase coherent bursts on multiple radios

I don't see how you can accomplish some of those things - without a tightly coupled timestamp and payload (dataset/buffer).

Those are the sorts of things that people want to do - and @mhennerich is correct - it requires both HDL and software (kernel and userspace) updates... If libiio 1.0 is that time - that's great.

Thanks
-robin

**Comment by pcercuei** [comment]
@rgetz We were talking about the "timestamp" in particular - so the possibility to program the time at which a given block of samples should be transmitted. Hence my suggestion of using a separate hardware register, since we can program the scheduled transmission time before enqueuing a block.

I was suggesting that the timestamp value should be expressed not in seconds, but in samples. This means having a sample counter in HDL, which would also help later with full meta-data support (as you could program actions at a specific sample in a buffer) as well as overflow / underflow detection.

About full meta-data support we decided months ago that it's just really packet data, so it's a protocol between the IP and the application: neither the driver / IIO nor Libiio need to know what's in there.

**Comment by catkira** [comment]
I also think the "unit" of timestamps should be samples. Therefore there  has to be a counter in the hdl core running with src_clk. The questions is what happens at sample rate changes, but I think that can be solved, by just resetting the counter everytime a sample rate change happens or alternatively high level driver code can handle this. Soapy driver for bladeRF does this by getting the hwCounter value before rate change and then getting the hwCounter value immediately after the hwRate change and then keeping an internal offset for all future timestamps (or something similar, not sure if I remember exactly).

Changing settings of the SDR IC in a synchronized fashion would be nice, that would expand the scope of the timestamp feature a lot and would go into tdd and sync territory for which there are separate solutions available atm.
However I can imagine a simple solution how to integrate everything in the timestamp feature:

- timestamp feature is implemented inside the axi_dmac core with a counter running at src_clk (= sample clock)
- axi_dmac core gets additional hw registers (counter value, flag) which are set when enqueueing a new block
- there could be a flag setting that tells the core to output the block data not to the dac or read not from the adc, but instead from an external port of the axi_adc core. This external port could be connected to gpio-pins of SDR ICs, or to and I2C core or directly to an I2C interface of an SDR IC to do bitbanging I2C. That way one could change settings in a synchronized way with the timestamp feature.
- regarding the linux driver and libiio I would integrate the new metadate into the sg_descriptor, because it has to be written to the axi_dmac core together with the current dma descriptor (which is also just written to some hw registers of the axi_dmac core).
- there is one caviat: if timestamping is done at the axi_dmac core level, it is not possible to easily get sample accuracy. This is because the cpack core puts multiple samples into one data word when one or more channels are disabled. The axi_dmac core would also not be allowed to just through superfluous samples away, because they might be needed if there is another read after the current one without any gap in between. I thought about this problem for quite a while, had many ideas like adding an early abort feature to the cpack core. But now I think it would be easiest to do that logic in the axi_dmac or libiio driver:
the driver will always round up samples in read or write requests so that are exact multiples of the axi_dmac input data width. axi_dmac driver or libiio would than have to internally buffer superfluous samples and prepend them to the next read or write if needed.
- as a benchmark for the timestamp feature I would use srsRAN, because it is open source and widely used. Plus there is already other SDR hardware like ettus und bladeRF that works with this software. srsRAN is using bladeRF via a SoapySDR driver, so the same could be done for Pluto and more powerful ADI devices.

**Comment by catkira** [comment]
I read the [ettus document](https://kb.ettus.com/Synchronizing_USRP_Events_Using_Timed_Commands_in_UHD) that @rgetz mentioned.
They use an absolute time, which makes sense if you want to do all sorts of timed commands. Because the sample clock is not well defined when the sample rate changes. With that in mind, it might be better to use the ctrl_clk of the axi_dmac for the counter. That would be equivalent to the `vita_time` in ettus then.

**Comment by rgetz** [comment]
> I was suggesting that the timestamp value should be expressed not in seconds, but in samples.

yes - agree 100% - the proper term should be "sample stamping" - but no one calls it that. The common term used across the industry is still "timestamp" (to reflect sample clocks) However - thinking this is wall time - is terrible - since your wall clock likely is going to run from different clocks across units, vs your sample clock, and will drift compared to sample clocks...

>This means having a sample counter in HDL, which would also help later with full meta-data support (as you could program actions at a specific sample in a buffer) as well as overflow / underflow detection.

Also agree - the software exposure in the kernel/user space/library needs to be done synchronously with the HDL.. Both from an architecture/design/implementation perspective. There isn't any point in thinking about SW without the HDL team.

There are basically two ways (I think?) to do things.
1. Add a header to each buffer
2. Add fences and resource barriers in the "stream". This is a concept that I learned about from Lars when he was looking at this a few years ago, and is something that the GPU programmers have been doing for a long time...

I don't know the complexity of implementing or complexity of using either. I can see the pro/con of each...

-Robin

**Comment by pcercuei** [comment]
So we had a meeting with our HDL people to discuss this matter.

The initial design we came up with is the following:
- One 64-bit counter in axi-dmac, running on the sample clock. It would need to be readable from a register too.
- A register area of NB_BLOCKS_MAX * 64-bit, containing timestamp values for each one of the blocks, indexed by the DMA hardware descriptor index.
- During a TX or RX transfer, the IP would read the corresponding timestamp from the registers area, wait until its value matches the internal counter, then perform the transfer. If the freerunning counter is already past the timestamp value, this is an underrun scenario, and the IP can raise an IRQ to the processor. In this case, the current counter's value is written back to the timestamp register (If there's no underrun the write wouldn't change the content of the register anyway).
- The HDL would have to crawl the DMA descriptors list, in order to find the next transfer, because the transfers could be submitted out-of-order. Unless we make it a requirement that the transfers must be in-order.

On the kernel side of things, I would imagine a IIO buffer property named "timestamp", which the userspace would write prior to enqueueing a new block (either with BLOCK_ENQUEUE_IOCTL with the old mmap API, or with IIO_DMABUF_ENQUEUE_IOCTL with the new dmabuf API). When setting up the DMA descriptor the kernel would then write this value to the registers area, at the offset that corresponds to the block about to get transferred.

I think it would make sense that the "timestamp" IIO attribute would be automatically updated every time a block is enqueued so that it doesn't have to be touched when doing regular gapless data streaming. The value updated would correspond to the value of the block's timestamp register after the enqueue (since it can be updated by HDL when there's an underrun) + the size in samples of the block.

In Libiio, this IIO attribute would be read / written like any other regular attribute, but we could have a dedicated wrapper function for this functionality.

This design would allow to program transfers very accurately relative to one another - e.g. a 300µs delay between two transfers - but for Libiio to program transfers in wall clock time (e.g. transfer this block in *exactly* 500µs from now) we need to know the queue's latency, aka. the time in samples between the moment a buffer is enqueued and the moment it will be processed. I think it would be enough to have a "counter" IIO buffer attribute which would be updated alongside the "timestamp" one, with the current value of the IP's sample counter. Libiio can then estimate the latency from these values.

@mhennerich did I forget anything?
@rgetz, @catkira thoughts?

**Comment by catkira** [comment]
How about the fixed number of samples issue when some channels are disabled? ( I have written about it above )

**Comment by pcercuei** [comment]
@catkira You mean this?
> there is one caviat: if timestamping is done at the axi_dmac core level, it is not possible to easily get sample accuracy. This is because the cpack core puts multiple samples into one data word when one or more channels are disabled. The axi_dmac core would also not be allowed to just through superfluous samples away, because they might be needed if there is another read after the current one without any gap in between. I thought about this problem for quite a while, had many ideas like adding an early abort feature to the cpack core.

I don't understand the problem, sorry. Unless something is really wrong, you should be able to request 3 16-bit samples from the DMA, and the last one will be padded with zeros.

**Comment by catkira** [comment]
lets the dma width is 64 bit like in pluto. One channel is disabled. How do you sent only 1 IQ pair? zero padding is bad, because a gap between two bursts might not be wanted.

**Comment by pcercuei** [comment]
You send one IQ pair in a 64-bit word padded with zeroes. I don't see the problem. You would only transfer the one IQ pair. The padding is, as its name suggests, just padding.

**Comment by catkira** [comment]
but then the dac sends out an unwanted 0 sample

**Comment by catkira** [comment]
I know its happening currently, but its not really a bug so far because fixes length transfers are not supported so far

**Comment by catkira** [comment]
I know hdl is not your main area of expertise, but by looking at what information the upack core gets from the dma core you can understand the problem without looking at hdl code.

**Comment by pcercuei** [comment]
Transfers of arbitrary lengths are supported and have been for a while, for instance libiio v0.24 has `iio_buffer_push_partial`.

I guess this issue is not really related to the timestamp API (more like tangent to it), you should probably open a new bug report on analogdevicesinc/linux.

**Comment by catkira** [comment]
but why in linux? its a design limitation of the upack and dma core.

**Comment by pcercuei** [comment]
On `analogdevicesinc/hdl` then.

**Comment by acostina** [comment]
We're currently thinking through possible architecture also on the HDL side.
During the above discussion, I don't think it was taken into consideration the fact that we have some designs in which we transfer more than one sample per clock. Also, in some designs, the clocks connected to the DMA are not directly related to sampling clock as we use an intermediary buffer capture/send data. Another aspect would be synchronizing multiple timers in multiple DMAs (both TX and Rx side) which we would probably want to do.
We'll need a bit more time to think about the architecture as we haven't focused on this recently in the HDL team and the people that developed and maintained the DMAC IP are no longer at ADI

**Comment by catkira** [comment]
@acostina I have done some modifications to the upack and dma core to solve this issue. I think its too much to discuss the details in this libiio issue.

**Comment by catkira** [comment]
@pcercuei 
It would be nice if the user can get a result from the initiated transfer, ie an error when the requested time has already passed or an overflow occured. Is it possible to get information from the axi_dmac back to the user when dequeueing a block? Or do You have an idea how it could be done?

**Comment by pcercuei** [comment]
Yes, with the design I explained in my big message above, Libiio knows when a transfer's requested time already passed or when an overflow/underflow occured, when *enqueueing* a block.

**Comment by catkira** [comment]
The design You propose in Your long post would only check if the timestamps are ok when they get enqueued. But it does not guarantee that the dma descriptors reach the FPGA in time. So, if I understand it correctly, it could happen, that everything appears to be fine on the linux side, but the time is already passed once the descriptor reaches the fpga. Also RX overflows can happen inside the FPGA, when You read from ADC and the DMA channel bandwidth is not enough so that an overflow happens. How can this information reach the user?

**Comment by catkira** [comment]
In the linux driver there is a function that handles transfer completed events [here](https://github.com/analogdevicesinc/linux/blob/master/drivers/dma/dma-axi-dmac.c#:~:text=static%20bool%20axi_dmac_transfer_done,unsigned%20int%20completed_transfers)
Inside this function one could read some additional registers from the FPGA like flag or transfer_result. They just have to reach the user somehow.
But these cases where time is passed in hardware, or overflows in hardware should be pretty rare. So one could just have the software checks inside libiio like You described and have dma-axi-dmac.c just print an error message when an overflow or time_passed event occured in hardware.

**Comment by pcercuei** [comment]
> it does not guarantee that the dma descriptors reach the FPGA in time
I don't know what you mean by that. There are no hardware DMA descriptors.

When you enqueue a block to the kernel, the kernel will write the block's requested timestamp to the block's own timestamp HDL register, add it to the DMA queue, then read back the HDL timestamp register. If it reads a different value, that means you have an under/overrun.

> Also RX overflows can happen inside the FPGA, when You read from ADC and the DMA channel bandwidth is not enough so that an overflow happens.
Can they though? That really sounds like a HDL or hardware problem. The DMA should be able to keep up with the hardware.

**Comment by catkira** [comment]
> I don't know what you mean by that. There are no hardware DMA descriptors.
> 
> When you enqueue a block to the kernel, the kernel will write the block's requested timestamp to the block's own timestamp HDL register, add it to the DMA queue, then read back the HDL timestamp register. If it reads a different value, that means you have an under/overrun.

What I mean by hardware dma descriptor is the bunch of registers that stores information like length, target_addr, dest_addr and potentially start_time inside the axi_dmac core.
I assume writing to the blocks own timestamp HDL will also take place in the axi_dmac kernel driver (dma-axi-dmac.c). But the only information that currrently reaches this driver are the enqueued blocks via the kernel DMA system. Furthermore there is currently no information flow back from dma-axi-dmac.c to the user. So if the comparison of written and read-back timestamp happens inside dma-axi-dmac.c, how could the user be notified about the result?
All the channel attributes are provided the DAC and ADC drivers ([cf_axi_adc_core.c](https://github.com/analogdevicesinc/linux/blob/master/drivers/iio/adc/cf_axi_adc_core.c) and [drivers/iio/frequency/cf_axi_dds.c](https://github.com/analogdevicesinc/linux/blob/master/drivers/iio/frequency/cf_axi_dds.c)) but they currently dont write anything to the registers inside the axi_dmac core. It would be possible to also let the DAC and ADC drivers write axi_dmac hardware registers, but it would make the whole design not so clean.

**Comment by catkira** [comment]
I think this can be closed with the summarization that its difficult to find a timestamp implementation that suits everybody and it is therefore out of the scope of libiio (for now).
